basic:
  user: user
  password: $2a$10$vVqrr5.POc1iibtERDkhLuqKHUZKJfRXZhYgI0BJxnheoPaRUHcbm
server:
  servlet:
    context-path: /api
  port: 8080
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:genericCode
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  activemq:
    user:
logging:
  level:
    org.springframework.security: DEBUG